apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-financial-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-financial
  template:
    metadata:
      labels:
        app: ms-financial
    spec:
      containers:
      - name: ms-financial-container
        image: dealmachine/financial-api:1
        workingDir: /usr/financial/api
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: ms-financial-configmap
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          periodSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3003
          periodSeconds: 5
          failureThreshold: 30
